#!/bin/bash

echo "=========================================="
echo "DigitalOcean Deployment Helper"
echo "=========================================="
echo ""

echo "Step 1: Generate JWT Secret Key"
echo "Run this command to generate a secure JWT secret:"
echo "  python3 -c 'import secrets; print(secrets.token_urlsafe(32))'"
echo ""
read -p "Enter your JWT secret key (or press Enter to generate): " jwt_secret

if [ -z "$jwt_secret" ]; then
    jwt_secret=$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))' 2>/dev/null)
    if [ -z "$jwt_secret" ]; then
        echo "Error: Could not generate JWT secret. Please install Python 3 or generate manually."
        exit 1
    fi
    echo "Generated JWT Secret: $jwt_secret"
fi

echo ""
echo "Step 2: Prepare for Deployment"
echo "=========================================="
echo ""
echo "1. Make sure your code is pushed to GitHub:"
echo "   git add ."
echo "   git commit -m 'Prepare for DigitalOcean deployment'"
echo "   git push origin main"
echo ""
echo "2. Go to DigitalOcean Dashboard:"
echo "   https://cloud.digitalocean.com/apps"
echo ""
echo "3. Click 'Create App' → 'GitHub'"
echo ""
echo "4. Select repository: shubhhh19/memory-layer"
echo "   Branch: main"
echo ""
echo "5. DigitalOcean will detect the .do/app.yaml file automatically"
echo "   OR configure manually using DIGITALOCEAN_DEPLOY.md guide"
echo ""
echo "6. Set these environment variables in DigitalOcean:"
echo ""
echo "   MEMORY_JWT_SECRET_KEY=$jwt_secret"
echo "   MEMORY_ALLOWED_ORIGINS=https://your-frontend-app.ondigitalocean.app"
echo ""
echo "   (Update ALLOWED_ORIGINS after frontend is deployed with actual URL)"
echo ""
echo "7. For frontend, set:"
echo "   NEXT_PUBLIC_API_BASE_URL=https://your-backend-app.ondigitalocean.app"
echo ""
echo "=========================================="
echo "After deployment:"
echo "=========================================="
echo ""
echo "1. Enable pgvector extension in PostgreSQL:"
echo "   - Go to your database in DigitalOcean"
echo "   - Use Console or connect via psql"
echo "   - Run: CREATE EXTENSION IF NOT EXISTS vector;"
echo ""
echo "2. Verify migrations ran (check build logs)"
echo ""
echo "3. Test your app:"
echo "   - Backend health: https://your-backend-app.ondigitalocean.app/v1/admin/health"
echo "   - Frontend: https://your-frontend-app.ondigitalocean.app"
echo ""
echo "For detailed instructions, see: DIGITALOCEAN_DEPLOY.md"
echo ""

